#!/usr/bin/env bash
# plugins/agentify/lib/audit_aggregate.sh — rebuilds audits/summary.json
# by extracting the fenced-JSON contract from every audits/*.md and rolling
# them up by severity / category / recurring titles.
#
# Usage:
#   bash audit_aggregate.sh <audits-dir>           # writes <dir>/summary.json
#   bash audit_aggregate.sh <audits-dir> --trends  # also writes <dir>/trends.md
#
# Output: audits/summary.json contains:
#   {
#     "generated_at": "...",
#     "total": N,
#     "by_severity": { "critical": ..., "major": ..., ... },
#     "by_category": { "bug": ..., ... },
#     "recurring":    [ { "title": "...", "count": K, "audits": [...] }, ... ],
#     "open_synthetic_findings": M
#   }

set -euo pipefail

# shellcheck source=_io.sh
. "$(dirname "${BASH_SOURCE[0]}")/_io.sh"

dir="${1:-}"
emit_trends=0
shift || true
while [ "$#" -gt 0 ]; do
	case "$1" in
	--trends) emit_trends=1 ;;
	esac
	shift
done

if [ -z "$dir" ] || [ ! -d "$dir" ]; then
	echo "audit_aggregate: usage: $0 <audits-dir> [--trends]" >&2
	exit 2
fi

# Extract ALL fenced JSON blocks from each audit doc (H18 fix: the old
# code's `exit` on the first closing fence captured only the first block
# per file and missed any subsequent ones — and any ```` ``` ```` inside
# the JSON itself ended the parse early). New awk state-machine walks
# every block, emits each into its own .Nfile so the aggregator picks up
# all of them.
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

shopt -s nullglob
for f in "$dir"/*.md; do
	[ -f "$f" ] || continue
	# Skip the rollup itself.
	[[ "$(basename "$f")" = "trends.md" ]] && continue
	awk -v outbase="$tmp/$(basename "$f")" '
		BEGIN { inblock = 0; idx = 0 }
		/^```json[[:space:]]*$/ { inblock = 1; idx = idx + 1; out = outbase "." idx ".json"; next }
		/^```[[:space:]]*$/ { if (inblock) { inblock = 0; close(out); out = "" } else { next }; next }
		inblock && out != "" { print >> out }
	' "$f"
	# Validate each extracted block; drop non-JSON.
	for blk in "$tmp/$(basename "$f")."*.json; do
		[ -f "$blk" ] || continue
		if ! jq empty "$blk" >/dev/null 2>&1; then
			rm -f "$blk"
		fi
	done
done
shopt -u nullglob

# Aggregate. H19 fix: the prior --slurpfile glob expansion
# (`--slurpfile audits "$tmp"/*.json`) only accepts ONE file per flag —
# the shell expanded multiple .json files into positional args, and jq
# interpreted the second one as the filter. With >1 audit the rollup
# silently emitted empty totals. Use `jq -s` over `cat` instead, which
# slurps an arbitrary count from stdin.
#
# B-7 fix: guard the glob expansion. The old code did
# `audits_concat=$(cat "$tmp"/*.json 2>/dev/null)` — with no .json files
# in $tmp, the glob stayed literal and `cat` exited 1 ("no such file").
# Under set -euo pipefail the script aborted on the assignment BEFORE
# reaching the `|| { minimal seed }` fallback at the end of the jq
# pipeline. The fallback was unreachable. A fresh `audits/` dir (e.g.
# the first CI run) now crashed the nightly audit-trend.yml job
# silently. Fix: enumerate via `compgen -G`, default to empty input
# (`[]`) when the directory is empty, and use _io.sh:atomic_write for
# both summary.json and trends.md so SIGINT mid-write doesn't tear
# either file.
if compgen -G "$tmp/*.json" >/dev/null; then
	audits_concat=$(cat "$tmp"/*.json)
else
	audits_concat="[]"
fi

_audit_aggregate__write_summary() {
	# Stdout: the aggregated JSON. Caller pipes into atomic_write.
	if [ "$audits_concat" = "[]" ]; then
		jq -n --arg now "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
			'{generated_at: $now, total: 0, by_severity: {}, by_category: {}, recurring: [], open_synthetic_findings: 0}'
		return
	fi
	jq --slurp --arg now "$(date -u +%Y-%m-%dT%H:%M:%SZ)" '
		. as $audits |
		def all_findings: [ $audits[] | .findings[]? ];
		def by_field(f): all_findings | group_by(.[f]) | map({key: .[0][f], value: length}) | from_entries;
		def recurring:
			all_findings
			| group_by(.title)
			| map(select(length >= 2))
			| map({title: .[0].title, count: length, severity: .[0].severity, category: .[0].category});
		{
			generated_at: $now,
			total: (all_findings | length),
			by_severity: by_field("severity"),
			by_category: by_field("category"),
			recurring:   recurring,
			open_synthetic_findings: ([
				$audits[]
				| select(.synthetic_source != "human")
				| .findings[]?
			] | length)
		}
	' <<<"$audits_concat"
}

atomic_write "$dir/summary.json" _audit_aggregate__write_summary

if [ "$emit_trends" -eq 1 ]; then
	_audit_aggregate__write_trends() {
		echo "# Audit trends"
		echo ""
		echo "Regenerated by audit_aggregate.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
		echo ""
		echo "## Headline"
		echo ""
		jq -r '
			"- Total findings across audits: \(.total)",
			"- Open synthetic findings (require human review): \(.open_synthetic_findings)"
		' "$dir/summary.json"
		echo ""
		echo "## By severity"
		echo ""
		jq -r '.by_severity | to_entries[] | "- \(.key): \(.value)"' "$dir/summary.json"
		echo ""
		echo "## Recurring patterns (≥2 audits)"
		echo ""
		jq -r '.recurring[]? | "- **\(.title)** — \(.count)× (\(.severity), \(.category))"' "$dir/summary.json"
	}
	atomic_write "$dir/trends.md" _audit_aggregate__write_trends
fi

printf '%s\n' "$dir/summary.json"
