#!/usr/bin/env bash
# plugins/agentify/lib/audit_aggregate.sh — rebuilds audits/summary.json
# by extracting the fenced-JSON contract from every audits/*.md and rolling
# them up by severity / category / recurring titles.
#
# Usage:
#   bash audit_aggregate.sh <audits-dir>           # writes <dir>/summary.json
#   bash audit_aggregate.sh <audits-dir> --trends  # also writes <dir>/trends.md
#
# Output: audits/summary.json contains:
#   {
#     "generated_at": "...",
#     "total": N,
#     "by_severity": { "critical": ..., "major": ..., ... },
#     "by_category": { "bug": ..., ... },
#     "recurring":    [ { "title": "...", "count": K, "audits": [...] }, ... ],
#     "open_synthetic_findings": M
#   }

set -euo pipefail

dir="${1:-}"
emit_trends=0
shift || true
while [ "$#" -gt 0 ]; do
	case "$1" in
	--trends) emit_trends=1 ;;
	esac
	shift
done

if [ -z "$dir" ] || [ ! -d "$dir" ]; then
	echo "audit_aggregate: usage: $0 <audits-dir> [--trends]" >&2
	exit 2
fi

# Extract the first fenced JSON block from each audit doc. Each audit
# embeds one such block conforming to finding-schema.json.
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

for f in "$dir"/*.md; do
	[ -f "$f" ] || continue
	# Skip the rollup itself.
	[[ "$(basename "$f")" = "trends.md" ]] && continue
	awk '
		BEGIN { inblock = 0 }
		/^```json[[:space:]]*$/ { inblock = 1; next }
		/^```[[:space:]]*$/      { if (inblock) { exit } }
		inblock { print }
	' "$f" >"$tmp/$(basename "$f").json"
	if ! jq empty "$tmp/$(basename "$f").json" >/dev/null 2>&1; then
		rm -f "$tmp/$(basename "$f").json"
	fi
done

# Aggregate.
jq -n --slurpfile audits "$tmp"/*.json --arg now "$(date -u +%Y-%m-%dT%H:%M:%SZ)" '
	def all_findings: [ $audits[] | .findings[]? ];
	def by_field(f): all_findings | group_by(.[f]) | map({key: .[0][f], value: length}) | from_entries;
	def recurring:
		all_findings
		| group_by(.title)
		| map(select(length >= 2))
		| map({title: .[0].title, count: length, severity: .[0].severity, category: .[0].category});
	{
		generated_at: $now,
		total: (all_findings | length),
		by_severity: by_field("severity"),
		by_category: by_field("category"),
		recurring:   recurring,
		open_synthetic_findings: ([
			$audits[]
			| select(.synthetic_source != "human")
			| .findings[]?
		] | length)
	}
' >"$dir/summary.json" 2>/dev/null || {
	# Empty / no audits — emit a minimal seed.
	jq -n --arg now "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
		'{generated_at: $now, total: 0, by_severity: {}, by_category: {}, recurring: [], open_synthetic_findings: 0}' \
		>"$dir/summary.json"
}

if [ "$emit_trends" -eq 1 ]; then
	{
		echo "# Audit trends"
		echo ""
		echo "Regenerated by audit_aggregate.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
		echo ""
		echo "## Headline"
		echo ""
		jq -r '
			"- Total findings across audits: \(.total)",
			"- Open synthetic findings (require human review): \(.open_synthetic_findings)"
		' "$dir/summary.json"
		echo ""
		echo "## By severity"
		echo ""
		jq -r '.by_severity | to_entries[] | "- \(.key): \(.value)"' "$dir/summary.json"
		echo ""
		echo "## Recurring patterns (≥2 audits)"
		echo ""
		jq -r '.recurring[]? | "- **\(.title)** — \(.count)× (\(.severity), \(.category))"' "$dir/summary.json"
	} >"$dir/trends.md"
fi

printf '%s\n' "$dir/summary.json"
